<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DotnetFhirConnect.Tools.GenFixtures</RootNamespace>
    <AssemblyName>GenFixtures</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DotnetFhirConnect\DotnetFhirConnect.csproj" />
  </ItemGroup>

</Project>
